# Generated by Django 5.1.6 on 2025-04-08 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_messsage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messsage',
            new_name='Message',
        ),
    ]
